name: Linters

on:
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        python-version: [ 2.7 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint-celery==0.3  pylint-django==0.7.2 pylint-plugin-utils==0.2.6 pylint==1.7.1 edx-lint==0.5.4 configparser==3.5.0  astroid==1.5.2 backports.functools-lru-cache==1.5 click-log==0.1.8  mccabe==0.6.1
      - id: files
        name: Run Pylint
        uses: jitterbit/get-changed-files@v1
      - run: |
          echo ::set-output name=RESULT_PYLINT::$(pylint `find ${{ steps.files.outputs.added_modified }} -type f -name "*.py"`)
        id: pylint
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            Pylint Result:
            ```
            ${{ steps.pylint.outputs.RESULT_PYLINT }}
            ```
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false
